CREATE DATABASE yelp IF NOT EXISTS;

USE yelp;

CREATE TABLE resturants IF NOT EXISTS(
    id INT NOT NULL AUTO INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE pictures IF NOT EXISTS(
    id INT NOT NULL AUTO INCREMENT PRIMARY KEY,
    url VARCHAR(255) NOT NULL,
    user_id INT NOT NULL FOREIGN KEY,
    resturant_id INT NOT NULL FOREIGN KEY,
    rating INT NULL
);

CREATE TABLE users IF NOT EXISTS(
    id INT NOT NULL AUTO INCREMENT PRIMARY KEY,
    user VARCHAR(25) NOT NULL,
    elite TINYINT NOT NULL,
    friends INT NOT NULL,
    reviews INT NOT NULL
);

